apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-html
data:
  index.html: |
    <html>
      <head><title>Welcome to Argo CD + NGINX</title></head>
      <body>
        <h1>Hello from ConfigMap!</h1>
      </body>
    </html>

